### ISSUE TITLE
Computer User Ship Placement

### ISSUE THREAD

**Issue by StarPerfect** [tylorschafer/battleships#14]
When I began working on the User class this morning, I ran our Gameplay file just to ensure my output was as expected and things were going good so far. The first time I did such, the output for the computer user said 'submarine placement invalid' meaning it went through the if elsif loop all 4 times and got an invalid placement. When i ran the program from scratch again, it worked fine with no invalid placement error. Maybe that was just a one-off error but we should look into that section of code and see about adding an iteration until true or something. We don't want our user ever experiencing that when they play.

**Comment by tylorschafer** [comment]
We can look at this together tomorrow. I think we just need to add an until loop to the computer placement. What I did for user placement was I set a local variable called valid_input = false. Then I create an until loop that said until valid_input == true. Then once the code gets to the point where it finds valid coordinates you tell it to place the ship then set valid_input = true. This should solve that issue
